// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type CheckpointTx struct {
	Txid                 string `json:"txid"`
	Tx                   string `json:"tx"`
	CommitmentTxid       string `json:"commitment_txid"`
	IsRootCommitmentTxid bool   `json:"is_root_commitment_txid"`
	OffchainTxid         string `json:"offchain_txid"`
}

type Conviction struct {
	ID           string         `json:"id"`
	Type         int64          `json:"type"`
	CreatedAt    int64          `json:"created_at"`
	ExpiresAt    sql.NullInt64  `json:"expires_at"`
	CrimeType    int64          `json:"crime_type"`
	CrimeRoundID string         `json:"crime_round_id"`
	CrimeReason  string         `json:"crime_reason"`
	Pardoned     bool           `json:"pardoned"`
	Script       sql.NullString `json:"script"`
}

type Intent struct {
	ID      sql.NullString `json:"id"`
	RoundID sql.NullString `json:"round_id"`
	Proof   sql.NullString `json:"proof"`
	Message sql.NullString `json:"message"`
}

type IntentWithInputsVw struct {
	Txid           sql.NullString `json:"txid"`
	Vout           sql.NullInt64  `json:"vout"`
	Pubkey         sql.NullString `json:"pubkey"`
	Amount         sql.NullInt64  `json:"amount"`
	ExpiresAt      sql.NullInt64  `json:"expires_at"`
	CreatedAt      sql.NullInt64  `json:"created_at"`
	CommitmentTxid sql.NullString `json:"commitment_txid"`
	SpentBy        sql.NullString `json:"spent_by"`
	Spent          sql.NullBool   `json:"spent"`
	Unrolled       sql.NullBool   `json:"unrolled"`
	Swept          sql.NullBool   `json:"swept"`
	Preconfirmed   sql.NullBool   `json:"preconfirmed"`
	SettledBy      sql.NullString `json:"settled_by"`
	ArkTxid        sql.NullString `json:"ark_txid"`
	IntentID       sql.NullString `json:"intent_id"`
	Commitments    interface{}    `json:"commitments"`
	ID             sql.NullString `json:"id"`
	RoundID        sql.NullString `json:"round_id"`
	Proof          sql.NullString `json:"proof"`
	Message        sql.NullString `json:"message"`
}

type IntentWithReceiversVw struct {
	IntentID       sql.NullString `json:"intent_id"`
	Pubkey         sql.NullString `json:"pubkey"`
	OnchainAddress sql.NullString `json:"onchain_address"`
	Amount         sql.NullInt64  `json:"amount"`
	ID             sql.NullString `json:"id"`
	RoundID        sql.NullString `json:"round_id"`
	Proof          sql.NullString `json:"proof"`
	Message        sql.NullString `json:"message"`
}

type OffchainTx struct {
	Txid              string         `json:"txid"`
	Tx                string         `json:"tx"`
	StartingTimestamp int64          `json:"starting_timestamp"`
	EndingTimestamp   int64          `json:"ending_timestamp"`
	ExpiryTimestamp   int64          `json:"expiry_timestamp"`
	FailReason        sql.NullString `json:"fail_reason"`
	StageCode         int64          `json:"stage_code"`
}

type OffchainTxVw struct {
	Txid                 string         `json:"txid"`
	Tx                   string         `json:"tx"`
	StartingTimestamp    int64          `json:"starting_timestamp"`
	EndingTimestamp      int64          `json:"ending_timestamp"`
	ExpiryTimestamp      int64          `json:"expiry_timestamp"`
	FailReason           sql.NullString `json:"fail_reason"`
	StageCode            int64          `json:"stage_code"`
	CheckpointTxid       string         `json:"checkpoint_txid"`
	CheckpointTx         string         `json:"checkpoint_tx"`
	CommitmentTxid       string         `json:"commitment_txid"`
	IsRootCommitmentTxid bool           `json:"is_root_commitment_txid"`
	OffchainTxid         string         `json:"offchain_txid"`
}

type Receiver struct {
	IntentID       string         `json:"intent_id"`
	Pubkey         sql.NullString `json:"pubkey"`
	OnchainAddress string         `json:"onchain_address"`
	Amount         int64          `json:"amount"`
}

type Round struct {
	ID                 string         `json:"id"`
	StartingTimestamp  int64          `json:"starting_timestamp"`
	EndingTimestamp    int64          `json:"ending_timestamp"`
	Ended              bool           `json:"ended"`
	Failed             bool           `json:"failed"`
	StageCode          int64          `json:"stage_code"`
	ConnectorAddress   string         `json:"connector_address"`
	Version            int64          `json:"version"`
	Swept              bool           `json:"swept"`
	VtxoTreeExpiration int64          `json:"vtxo_tree_expiration"`
	FailReason         sql.NullString `json:"fail_reason"`
}

type RoundIntentsVw struct {
	ID      sql.NullString `json:"id"`
	RoundID sql.NullString `json:"round_id"`
	Proof   sql.NullString `json:"proof"`
	Message sql.NullString `json:"message"`
}

type RoundTxsVw struct {
	Txid     sql.NullString `json:"txid"`
	Tx       sql.NullString `json:"tx"`
	RoundID  sql.NullString `json:"round_id"`
	Type     sql.NullString `json:"type"`
	Position sql.NullInt64  `json:"position"`
	Children sql.NullString `json:"children"`
}

type RoundWithCommitmentTxVw struct {
	ID                 string         `json:"id"`
	StartingTimestamp  int64          `json:"starting_timestamp"`
	EndingTimestamp    int64          `json:"ending_timestamp"`
	Ended              bool           `json:"ended"`
	Failed             bool           `json:"failed"`
	StageCode          int64          `json:"stage_code"`
	ConnectorAddress   string         `json:"connector_address"`
	Version            int64          `json:"version"`
	Swept              bool           `json:"swept"`
	VtxoTreeExpiration int64          `json:"vtxo_tree_expiration"`
	FailReason         sql.NullString `json:"fail_reason"`
	Txid               string         `json:"txid"`
	Tx                 string         `json:"tx"`
	RoundID            string         `json:"round_id"`
	Type               string         `json:"type"`
	Position           int64          `json:"position"`
	Children           sql.NullString `json:"children"`
}

type ScheduledSession struct {
	ID                   int64 `json:"id"`
	StartTime            int64 `json:"start_time"`
	EndTime              int64 `json:"end_time"`
	Period               int64 `json:"period"`
	Duration             int64 `json:"duration"`
	RoundMinParticipants int64 `json:"round_min_participants"`
	RoundMaxParticipants int64 `json:"round_max_participants"`
	UpdatedAt            int64 `json:"updated_at"`
}

type Tx struct {
	Txid     string         `json:"txid"`
	Tx       string         `json:"tx"`
	RoundID  string         `json:"round_id"`
	Type     string         `json:"type"`
	Position int64          `json:"position"`
	Children sql.NullString `json:"children"`
}

type Vtxo struct {
	Txid           string         `json:"txid"`
	Vout           int64          `json:"vout"`
	Pubkey         string         `json:"pubkey"`
	Amount         int64          `json:"amount"`
	ExpiresAt      int64          `json:"expires_at"`
	CreatedAt      int64          `json:"created_at"`
	CommitmentTxid string         `json:"commitment_txid"`
	SpentBy        sql.NullString `json:"spent_by"`
	Spent          bool           `json:"spent"`
	Unrolled       bool           `json:"unrolled"`
	Swept          bool           `json:"swept"`
	Preconfirmed   bool           `json:"preconfirmed"`
	SettledBy      sql.NullString `json:"settled_by"`
	ArkTxid        sql.NullString `json:"ark_txid"`
	IntentID       sql.NullString `json:"intent_id"`
}

type VtxoCommitmentTxid struct {
	VtxoTxid       string `json:"vtxo_txid"`
	VtxoVout       int64  `json:"vtxo_vout"`
	CommitmentTxid string `json:"commitment_txid"`
}

type VtxoVw struct {
	Txid           string         `json:"txid"`
	Vout           int64          `json:"vout"`
	Pubkey         string         `json:"pubkey"`
	Amount         int64          `json:"amount"`
	ExpiresAt      int64          `json:"expires_at"`
	CreatedAt      int64          `json:"created_at"`
	CommitmentTxid string         `json:"commitment_txid"`
	SpentBy        sql.NullString `json:"spent_by"`
	Spent          bool           `json:"spent"`
	Unrolled       bool           `json:"unrolled"`
	Swept          bool           `json:"swept"`
	Preconfirmed   bool           `json:"preconfirmed"`
	SettledBy      sql.NullString `json:"settled_by"`
	ArkTxid        sql.NullString `json:"ark_txid"`
	IntentID       sql.NullString `json:"intent_id"`
	Commitments    interface{}    `json:"commitments"`
}
