version: "2"

run:
  timeout: 5m
  tests: true

linters:
  disable:
    # TODO disable only the "ST1001: should not use dot imports (staticcheck)" rule
    - staticcheck

formatters:
  enable:
    - gofmt
    - goimports
    - golines
  settings:
    golines:
      max-len: 100