CREATE TABLE IF NOT EXISTS intent_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
    offchain_input_fee_program TEXT NOT NULL DEFAULT '',
    onchain_input_fee_program TEXT NOT NULL DEFAULT '',
    offchain_output_fee_program TEXT NOT NULL DEFAULT '',
    onchain_output_fee_program TEXT NOT NULL DEFAULT ''
);

-- add index on created_at for faster retrieval of latest fees
CREATE INDEX IF NOT EXISTS idx_intent_fees_created_at ON intent_fees (created_at);