CREATE TABLE IF NOT EXISTS settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id = 1),
    session_duration BIGINT NOT NULL DEFAULT 0,
    unrolled_vtxo_min_expiry_margin BIGINT NOT NULL DEFAULT 0,
    ban_threshold BIGINT NOT NULL DEFAULT 0,
    ban_duration BIGINT NOT NULL DEFAULT 0,
    unilateral_exit_delay BIGINT NOT NULL DEFAULT 0,
    public_unilateral_exit_delay BIGINT NOT NULL DEFAULT 0,
    checkpoint_exit_delay BIGINT NOT NULL DEFAULT 0,
    boarding_exit_delay BIGINT NOT NULL DEFAULT 0,
    vtxo_tree_expiry BIGINT NOT NULL DEFAULT 0,
    round_min_participants_count BIGINT NOT NULL DEFAULT 0,
    round_max_participants_count BIGINT NOT NULL DEFAULT 0,
    vtxo_min_amount BIGINT NOT NULL DEFAULT 0,
    vtxo_max_amount BIGINT NOT NULL DEFAULT 0,
    utxo_min_amount BIGINT NOT NULL DEFAULT 0,
    utxo_max_amount BIGINT NOT NULL DEFAULT 0,
    settlement_min_expiry_gap BIGINT NOT NULL DEFAULT 0,
    vtxo_no_csv_validation_cutoff_date BIGINT NOT NULL DEFAULT 0,
    max_tx_weight BIGINT NOT NULL DEFAULT 0,
    max_op_return_outputs BIGINT NOT NULL DEFAULT 0,
    asset_tx_max_weight_ratio REAL NOT NULL DEFAULT 0,
    note_uri_prefix TEXT NOT NULL DEFAULT '',
    -- scheduled session: all-zero means no scheduled session (matches ScheduledSession.IsEmpty)
    scheduled_session_start_time BIGINT NOT NULL DEFAULT 0,
    scheduled_session_end_time BIGINT NOT NULL DEFAULT 0,
    scheduled_session_period BIGINT NOT NULL DEFAULT 0,
    scheduled_session_duration BIGINT NOT NULL DEFAULT 0,
    scheduled_session_round_min_participants_count BIGINT NOT NULL DEFAULT 0,
    scheduled_session_round_max_participants_count BIGINT NOT NULL DEFAULT 0,
    -- batch fees: empty program means the fee is disabled
    batch_onchain_input_fee TEXT NOT NULL DEFAULT '',
    batch_offchain_input_fee TEXT NOT NULL DEFAULT '',
    batch_onchain_output_fee TEXT NOT NULL DEFAULT '',
    batch_offchain_output_fee TEXT NOT NULL DEFAULT '',
    build_version_header TEXT NOT NULL DEFAULT '',
    build_version_header_required BOOLEAN NOT NULL DEFAULT FALSE,
    digest_header_required BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at BIGINT NOT NULL
);

-- Append-only audit log of settings changes. changed_fields holds the changelog
-- returned by Settings.Update; settings holds a full JSONB snapshot taken after
-- the change (built from the settings row via to_jsonb), so this table stays
-- decoupled from the settings columns.
CREATE TABLE IF NOT EXISTS settings_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_at BIGINT NOT NULL,
    changed_fields TEXT[] NOT NULL,
    settings JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_settings_history_changed_at
    ON settings_history (changed_at);
CREATE INDEX IF NOT EXISTS idx_settings_history_changed_fields
    ON settings_history USING GIN (changed_fields);
