package pgdb_test

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/arkade-os/arkd/internal/core/domain"
	pgdb "github.com/arkade-os/arkd/internal/infrastructure/db/postgres"
	arklib "github.com/arkade-os/arkd/pkg/ark-lib"
	_ "github.com/lib/pq"
	"github.com/stretchr/testify/require"
)

const seedTestDSN = "postgres://root:secret@localhost:5432/event?sslmode=disable"

func seedDefaults(t *testing.T) domain.Settings {
	t.Helper()
	// ParseRelativeLocktime returns (RelativeLocktime, rounded). 512/1024/1536 are
	// exact multiples of MinAllowedSequence, so rounded must be false.
	exit, rounded := arklib.ParseRelativeLocktime(512)
	require.False(t, rounded)
	tree, rounded := arklib.ParseRelativeLocktime(1024)
	require.False(t, rounded)
	boarding, rounded := arklib.ParseRelativeLocktime(1536)
	require.False(t, rounded)
	return domain.Settings{
		SessionDuration:             30 * time.Second,
		UnrolledVtxoMinExpiryMargin: 30 * time.Second,
		UnilateralExitDelay:         exit,
		PublicUnilateralExitDelay:   exit,
		CheckpointExitDelay:         exit,
		BoardingExitDelay:           boarding,
		VtxoTreeExpiry:              tree,
		RoundMinParticipantsCount:   1,
		RoundMaxParticipantsCount:   10,
		VtxoMinAmount:               1,
		VtxoMaxAmount:               -1,
		UtxoMinAmount:               1,
		UtxoMaxAmount:               -1,
		MaxTxWeight:                 400_000,
		AssetTxMaxWeightRatio:       0.5,
		UpdatedAt:                   time.Unix(1_700_000_000, 0),
	}
}

// setupSeedTables creates the settings + legacy tables fresh, dropping any leftovers
// first so the test is repeatable against a shared postgres instance.
func setupSeedTables(t *testing.T, db *sql.DB) {
	t.Helper()
	dropSeedTables(t, db)
	_, err := db.Exec(`
CREATE TABLE settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id = 1),
    session_duration BIGINT NOT NULL DEFAULT 0,
    unrolled_vtxo_min_expiry_margin BIGINT NOT NULL DEFAULT 0,
    ban_threshold BIGINT NOT NULL DEFAULT 0,
    ban_duration BIGINT NOT NULL DEFAULT 0,
    unilateral_exit_delay BIGINT NOT NULL DEFAULT 0,
    public_unilateral_exit_delay BIGINT NOT NULL DEFAULT 0,
    checkpoint_exit_delay BIGINT NOT NULL DEFAULT 0,
    boarding_exit_delay BIGINT NOT NULL DEFAULT 0,
    vtxo_tree_expiry BIGINT NOT NULL DEFAULT 0,
    round_min_participants_count BIGINT NOT NULL DEFAULT 0,
    round_max_participants_count BIGINT NOT NULL DEFAULT 0,
    vtxo_min_amount BIGINT NOT NULL DEFAULT 0,
    vtxo_max_amount BIGINT NOT NULL DEFAULT 0,
    utxo_min_amount BIGINT NOT NULL DEFAULT 0,
    utxo_max_amount BIGINT NOT NULL DEFAULT 0,
    settlement_min_expiry_gap BIGINT NOT NULL DEFAULT 0,
    vtxo_no_csv_validation_cutoff_date BIGINT NOT NULL DEFAULT 0,
    max_tx_weight BIGINT NOT NULL DEFAULT 0,
    max_op_return_outputs BIGINT NOT NULL DEFAULT 0,
    asset_tx_max_weight_ratio REAL NOT NULL DEFAULT 0,
    note_uri_prefix TEXT NOT NULL DEFAULT '',
    scheduled_session_start_time BIGINT NOT NULL DEFAULT 0,
    scheduled_session_end_time BIGINT NOT NULL DEFAULT 0,
    scheduled_session_period BIGINT NOT NULL DEFAULT 0,
    scheduled_session_duration BIGINT NOT NULL DEFAULT 0,
    scheduled_session_round_min_participants_count BIGINT NOT NULL DEFAULT 0,
    scheduled_session_round_max_participants_count BIGINT NOT NULL DEFAULT 0,
    batch_onchain_input_fee TEXT NOT NULL DEFAULT '',
    batch_offchain_input_fee TEXT NOT NULL DEFAULT '',
    batch_onchain_output_fee TEXT NOT NULL DEFAULT '',
    batch_offchain_output_fee TEXT NOT NULL DEFAULT '',
    updated_at BIGINT NOT NULL
);
CREATE TABLE intent_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at BIGINT NOT NULL DEFAULT 0,
    offchain_input_fee_program TEXT NOT NULL DEFAULT '',
    onchain_input_fee_program TEXT NOT NULL DEFAULT '',
    offchain_output_fee_program TEXT NOT NULL DEFAULT '',
    onchain_output_fee_program TEXT NOT NULL DEFAULT ''
);
CREATE TABLE scheduled_session (
    id SERIAL PRIMARY KEY,
    start_time BIGINT NOT NULL,
    end_time BIGINT NOT NULL,
    period BIGINT NOT NULL,
    duration BIGINT NOT NULL,
    round_min_participants BIGINT NOT NULL DEFAULT 0,
    round_max_participants BIGINT NOT NULL DEFAULT 0,
    updated_at BIGINT NOT NULL
);`)
	require.NoError(t, err)
}

func dropSeedTables(t *testing.T, db *sql.DB) {
	t.Helper()
	_, err := db.Exec(`
		DROP TABLE IF EXISTS settings;
		DROP TABLE IF EXISTS intent_fees;
		DROP TABLE IF EXISTS scheduled_session;`)
	require.NoError(t, err)
}

func TestPgSeedSettings_BackfillsLegacy(t *testing.T) {
	ctx := context.Background()
	db, err := sql.Open("postgres", seedTestDSN)
	require.NoError(t, err)
	t.Cleanup(func() {
		dropSeedTables(t, db)
		_ = db.Close()
	})

	setupSeedTables(t, db)

	_, err = db.Exec(`
		INSERT INTO intent_fees
			(created_at, offchain_input_fee_program, onchain_input_fee_program,
			 offchain_output_fee_program, onchain_output_fee_program)
		VALUES (100, '0.1', '0.2', '0.3', '0.4');`)
	require.NoError(t, err)

	// past-dated recurring session: proves future-start validation no longer blocks seed.
	_, err = db.Exec(`
		INSERT INTO scheduled_session
			(start_time, end_time, period, duration, round_min_participants,
			 round_max_participants, updated_at)
		VALUES (1600000000, 1600003600, 3600, 60, 2, 5, 1600000000);`)
	require.NoError(t, err)

	require.NoError(t, pgdb.SeedSettings(ctx, db, seedDefaults(t)))

	var (
		batchOffchainIn string
		ssStart         int64
		ssRoundMin      int64
	)
	err = db.QueryRow(`
		SELECT batch_offchain_input_fee, scheduled_session_start_time,
		       scheduled_session_round_min_participants_count
		FROM settings WHERE id = 1`).Scan(&batchOffchainIn, &ssStart, &ssRoundMin)
	require.NoError(t, err)
	require.Equal(t, "0.1", batchOffchainIn)
	require.Equal(t, int64(1600000000), ssStart)
	require.Equal(t, int64(2), ssRoundMin)

	var feeCount, ssCount int
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM intent_fees`).Scan(&feeCount))
	require.NoError(t, db.QueryRow(`SELECT COUNT(*) FROM scheduled_session`).Scan(&ssCount))
	require.Equal(t, 0, feeCount)
	require.Equal(t, 0, ssCount)
}

func TestPgSeedSettings_Idempotent(t *testing.T) {
	ctx := context.Background()
	db, err := sql.Open("postgres", seedTestDSN)
	require.NoError(t, err)
	t.Cleanup(func() {
		dropSeedTables(t, db)
		_ = db.Close()
	})

	setupSeedTables(t, db)

	require.NoError(t, pgdb.SeedSettings(ctx, db, seedDefaults(t)))
	_, err = db.Exec(`UPDATE settings SET session_duration = 999 WHERE id = 1`)
	require.NoError(t, err)

	require.NoError(t, pgdb.SeedSettings(ctx, db, seedDefaults(t)))

	var sessionDuration int64
	require.NoError(t, db.QueryRow(
		`SELECT session_duration FROM settings WHERE id = 1`).Scan(&sessionDuration))
	require.Equal(t, int64(999), sessionDuration)
}
