// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1IndexerChain v1 indexer chain
//
// swagger:model v1IndexerChain
type V1IndexerChain struct {

	// expires at
	ExpiresAt string `json:"expiresAt,omitempty"`

	// txid
	Txid string `json:"txid,omitempty"`
}

// Validate validates this v1 indexer chain
func (m *V1IndexerChain) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1 indexer chain based on context it is used
func (m *V1IndexerChain) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1IndexerChain) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1IndexerChain) UnmarshalBinary(b []byte) error {
	var res V1IndexerChain
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
